spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_puppit?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: user

server:
  port: 8080

logging:
  level:
    org.puppit: DEBUG
    org.springframework.web: DEBUG

cors:
  allowed-origins: http://localhost:3000,http://localhost:80

